[plugin]
# The open-source Git repository that your code is hosted on.
# Must be visible to the external web, but doesn't have to be GitHub.
# If `git clone` accepts it, it will work here, with the caveat that it
# must be accessible (i.e. no `git` or `ssh` URLs, as the agent cannot clone those)
repository = "https://github.com/NightmareXIV/NotificationMaster.git"
# The commit to check out and build from the repository.
commit = "460a9c9f7e0c4ae3c9ee55153b0b43b542806f3d"
# The people authorised to update this manifest (e.g. who can deploy updates). These are GitHub usernames.
owners = [
    "Limiana"
]
